package com.example.beihangQA_test;

public class Constant {
//	public static final String onlineuserURL="http://124.205.18.167:80/Campus/RequestOnlineUsersListServlet";
//	public static final String publish_newsURL="http://124.205.18.167:80/Campus/PublishNewsServlet";
//	public static final String loginURL="http://124.205.18.167:80/Campus/LoginServlet";
//	public static final String registerURL="http://124.205.18.167:80/Campus/RegisterServlet";
//	public static final String newsShowURL = "http://124.205.18.167:80/Campus/RequestNewsDetailServlet"; 
//	public static final String publish_newsCommentURL="http://124.205.18.167:80/Campus/PublishCommentServlet";
//	public static final String requestNewsListURL="http://124.205.18.167:80/Campus/RequestNewsServlet"; 
//	public static final String reportlocationURL="http://124.205.18.167:80/Campus/PushServlet";//GetLocationReportServlet";
//	public static final String NOTIFICATION_ICON = "NOTIFICATION_ICON";
//	public static final String SETTINGS_SOUND_ENABLED = "SETTINGS_SOUND_ENABLED";
//	public static final String SETTINGS_VIBRATE_ENABLED = "SETTINGS_VIBRATE_ENABLED";
//	public static final String SETTINGS_TOAST_ENABLED = "SETTINGS_TOAST_ENABLED";
//	public static final String homepageMyNewsListURL="http://124.205.18.167:80/Campus/RequestNewsListOfUser";
//	public static final String homepageMyCommentListURL="http://124.205.18.167:80/Campus/RequestCommentsListOfUser";
//	public static final String homepageInfoURL="http://124.205.18.167:80/Campus/RequestUserInfoServlet";
//	public static final String userIDtouserNameURL="http://124.205.18.167:80/Campus/GetNameById";
//	public static final String homepageMyQAListURL="http://124.205.18.167:80/Campus/RequestQestionListOfUser"; 
//	public static final String homepageEditInfoURL="http://124.205.18.167:80/Campus/UpdateUserInfoServlet"; 
//	public static final String homepageMyAnswerListURL="http://124.205.18.167:80/Campus/RequestAnswerListOfUser";
//	public static final String ConfirmAnswerURL="http://124.205.18.167:80/Campus/ConfirmAnswerServlet";
//	public static final String homepageMyNewsListDeleteURL="http://124.205.18.167:80/Campus/DeleteNewsServlet";
//	public static final String homepageMyQAListDeleteURL="http://124.205.18.167:80/Campus/DeleteQuestionServlet";
//	public static final String MAIN_IP = "http://124.205.18.167:80/Campus/AskAndAnswer";
	
//	public static final String onlineuserURL="http://192.168.3.52:8080/Campus/RequestOnlineUsersListServlet";
//	public static final String publish_newsURL="http://192.168.3.52:8080/Campus/PublishNewsServlet";
//	public static final String loginURL="http://192.168.3.52:8080/Campus/LoginServlet";
//	public static final String registerURL="http://192.168.3.52:8080/Campus/RegisterServlet";
//	public static final String newsShowURL = "http://192.168.3.52:8080/Campus/RequestNewsDetailServlet"; 
//	public static final String publish_newsCommentURL="http://192.168.3.52:8080/Campus/PublishCommentServlet";
//	public static final String requestNewsListURL="http://192.168.3.52:8080/Campus/RequestNewsServlet"; 
//	public static final String reportlocationURL="http://192.168.3.52:8080/Campus/PushServlet";//GetLocationReportServlet";
//	public static final String NOTIFICATION_ICON = "NOTIFICATION_ICON";
//	public static final String SETTINGS_SOUND_ENABLED = "SETTINGS_SOUND_ENABLED";
//	public static final String SETTINGS_VIBRATE_ENABLED = "SETTINGS_VIBRATE_ENABLED";
//	public static final String SETTINGS_TOAST_ENABLED = "SETTINGS_TOAST_ENABLED";
//	public static final String homepageMyNewsListURL="http://192.168.3.52:8080/Campus/RequestNewsListOfUser";
//	public static final String homepageMyCommentListURL="http://192.168.3.52:8080/Campus/RequestCommentsListOfUser";
//	public static final String homepageInfoURL="http://192.168.3.52:8080/Campus/RequestUserInfoServlet";
//	public static final String userIDtouserNameURL="http://192.168.3.52:8080/Campus/GetNameById";
//	public static final String homepageMyQAListURL="http://192.168.3.52:8080/Campus/RequestQestionListOfUser"; 
//	public static final String homepageEditInfoURL="http://192.168.3.52:8080/Campus/UpdateUserInfoServlet"; 
//	public static final String homepageMyAnswerListURL="http://192.168.3.52:8080/Campus/RequestAnswerListOfUser";
//	public static final String ConfirmAnswerURL="http://192.168.3.52:8080/Campus/ConfirmAnswerServlet";
//	public static final String homepageMyNewsListDeleteURL="http://192.168.3.52:8080/Campus/DeleteNewsServlet";
//	public static final String homepageMyQAListDeleteURL="http://192.168.3.52:8080/Campus/DeleteQuestionServlet";
//	public static final String MAIN_IP = "http://192.168.3.52:8080/Campus/AskAndAnswer";
	
	
	public static final String onlineuserURL="http://112.124.46.148:80/Campus/RequestOnlineUsersListServlet";
	public static final String publish_newsURL="http://112.124.46.148:80/Campus/PublishNewsServlet";
	public static final String loginURL="http://112.124.46.148:80/Campus/LoginServlet";
	public static final String registerURL="http://112.124.46.148:80/Campus/RegisterServlet";
	public static final String newsShowURL = "http://112.124.46.148:80/Campus/RequestNewsDetailServlet"; 
	public static final String publish_newsCommentURL="http://112.124.46.148:80/Campus/PublishCommentServlet";
	public static final String requestNewsListURL="http://112.124.46.148:80/Campus/RequestNewsServlet"; 
	public static final String reportlocationURL="http://112.124.46.148:80/Campus/PushServlet";//GetLocationReportServlet";
	public static final String NOTIFICATION_ICON = "NOTIFICATION_ICON";
	public static final String SETTINGS_SOUND_ENABLED = "SETTINGS_SOUND_ENABLED";
	public static final String SETTINGS_VIBRATE_ENABLED = "SETTINGS_VIBRATE_ENABLED";
	public static final String SETTINGS_TOAST_ENABLED = "SETTINGS_TOAST_ENABLED";
	public static final String homepageMyNewsListURL="http://112.124.46.148:80/Campus/RequestNewsListOfUser";
	public static final String homepageMyCommentListURL="http://112.124.46.148:80/Campus/RequestCommentsListOfUser";
	public static final String homepageInfoURL="http://112.124.46.148:80/Campus/RequestUserInfoServlet";
	public static final String userIDtouserNameURL="http://112.124.46.148:80/Campus/GetNameById";
	public static final String homepageMyQAListURL="http://112.124.46.148:80/Campus/RequestQestionListOfUser"; 
	public static final String homepageEditInfoURL="http://112.124.46.148:80/Campus/UpdateUserInfoServlet"; 
	public static final String homepageMyAnswerListURL="http://112.124.46.148:80/Campus/RequestAnswerListOfUser";
	public static final String ConfirmAnswerURL="http://112.124.46.148:80/Campus/ConfirmAnswerServlet";
	public static final String homepageMyNewsListDeleteURL="http://112.124.46.148:80/Campus/DeleteNewsServlet";
	public static final String homepageMyQAListDeleteURL="http://112.124.46.148:80/Campus/DeleteQuestionServlet";
	public static final String MAIN_IP = "http://112.124.46.148:80/Campus/AskAndAnswer";
	
	
public static String nickname=null;
public static String credit=null;
public static String rank=null;
public static String username=null;
public static String email=null;
public static String department=null;
public static String stuclass=null;
public static String registerTime=null;
public static String gender=null;
public static String birthday=null;
public static String group=null;
public static String rqlimit=null;
public static String studentId=null;
public static String userID=null;
public static String password=null;
public static int x=0;
public static int y=0;
}
